spring.application.name=expense-planner

spring.datasource.url=jdbc:mysql://localhost:3306/expense_planner
spring.datasource.username=root
spring.datasource.password=@//jibruski9
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=lashga-afd-ghq-rwg-qwqasg2134h-32-4ew
jwt.expiration=3600000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=example@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontent.url=localhost:8080